name: FlappyBirds in Python

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '**'

jobs:
  unit_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.x]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame coverage

    - name: Run unit tests
      run: |
        coverage run -m unittest discover -s tests/unit -p "*.py"

    - name: Generate coverage report for unit tests
      run: |
        coverage report
        coverage html

    - name: Upload coverage report for unit tests
      uses: actions/upload-artifact@v2
      with:
        name: coverage-html-report-unit-${{ matrix.os }}
        path: htmlcov

  integration_tests:
    runs-on: ${{ matrix.os }}
    needs: unit_tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.x]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame coverage

    - name: Run integration tests
      run: |
        coverage run -m unittest discover -s tests/integration -p "*.py"

    - name: Generate coverage report for integration tests
      run: |
        coverage report
        coverage html

    - name: Upload coverage report for integration tests
      uses: actions/upload-artifact@v2
      with:
        name: coverage-html-report-integration-${{ matrix.os }}
        path: htmlcov

  deploy:
    runs-on: ubuntu-latest
    needs: [unit_tests, integration_tests]
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame pyinstaller

    - name: Generate executable
      run: |
        pyinstaller --onefile FlappyBird.py

    - name: Deploy to production
      env:
        EXECUTABLE_PATH: dist/FlappyBird
      run: |
        echo "Implementar script de deploy aqui"