name: Python application CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.x]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame coverage pyinstaller

    - name: Run unit tests
      run: |
        coverage run -m unittest discover -s tests/unit -p "*.py"

    - name: Run integration tests
      run: |
        coverage run -m unittest discover -s tests/integration -p "*.py"

    - name: Generate coverage report
      run: |
        coverage report
        coverage html

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-html-report-${{ matrix.os }}
        path: htmlcov

    - name: Generate executable
      run: |
        pyinstaller --onefile FlappyBird.py

    - name: Upload executable
      uses: actions/upload-artifact@v2
      with:
        name: FlappyBird-executable-${{ matrix.os }}
        path: dist/FlappyBird

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame pyinstaller

    - name: Generate executable
      run: |
        pyinstaller --onefile FlappyBird.py

    - name: Deploy to production
      env:
        EXECUTABLE_PATH: dist/FlappyBird
      run: |
        echo "Implementar script de deploy aqui"