name: Python application

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.x]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame coverage pyinstaller

    - name: Run tests
      run: |
        coverage run -m unittest discover -s tests -p "*.py"

    - name: Generate coverage report
      run: |
        coverage report
        coverage html

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-html-report-${{ matrix.os }}
        path: htmlcov

    - name: Generate executable
      run: |
        pyinstaller --onefile FlappyBird.py

    - name: Upload executable
      uses: actions/upload-artifact@v2
      with:
        name: FlappyBird-executable-${{ matrix.os }}
        path: dist/FlappyBird